spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:postgresql://localhost:5433/registrationDb
    username: reguser
    password: regpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8080

